import Head from "next/head";
import Link from "next/link";

import { ArticleItem, Layout, HeroArticle } from "@/shared/components";
import { Article } from "@/shared/models";
import {
  getAllArticles,
  getAllTags,
  getArchives,
} from "@/shared/services/ArticleService";
import { formatDate } from "@/shared/services/DateService";
import { markdownToHtml } from "@/shared/services/MarkdownService";

export type HomeProps = {
  heroArticle: Article;
  articles: Article[];
  tags: string[];
  archives: { [key: string]: { count: number; year: string; month: string } };
};

const Home = ({ articles, heroArticle, tags, archives }: HomeProps) => {
  return (
    <Layout>
      <Head>
        <title>I am mitsuruog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroArticle article={heroArticle} />
      <ul className="flex flex-col gap-8">
        <li>
          <h2 className="text-2xl font-bold">Recent Posts</h2>
        </li>
        {articles.map((article) => (
          <li key={article.slug}>
            <ArticleItem article={article}></ArticleItem>
          </li>
        ))}
        <li>
          <Link href="/page/1">
            <a>Read More</a>
          </Link>
        </li>
      </ul>
      <div className="flex gap-8">
        <div className="w-2/3 flex flex-col gap-4">
          <h4 className="text-xl font-bold">Tags</h4>
          <div className="flex flex-wrap gap-x-2 gap-y-1 text-sm text-slate-900">
            {tags.map((tag, index) => (
              <Link
                key={`tag${index}`}
                as={`/tags/${tag}`}
                href="tags/[tagName]"
              >
                <a>{tag}</a>
              </Link>
            ))}
          </div>
        </div>
        <div className="w-1/3 flex flex-col gap-2">
          <h4 className="text-xl font-bold">Archives</h4>
          <div className="flex flex-col gap-1 text-sm text-slate-900">
            {Object.keys(archives).map((key) => {
              const { year, month, count } = archives[key];
              return (
                <Link
                  key={key}
                  as={`/archives/${year}/${month}`}
                  href="/archives/[year]/[month]"
                >
                  <a>{`${formatDate(key, "MMMM, YYYY")} (${count})`}</a>
                </Link>
              );
            })}
          </div>
        </div>
      </div>
    </Layout>
  );
};

export const getStaticProps = async () => {
  const articles = getAllArticles([
    "slug",
    "title",
    "date",
    "thumbnail",
    "timeReading",
    "content",
    "tags",
  ]);

  const tags = getAllTags();
  const archives = getArchives();

  const heroArticle = articles[0];
  const content = await markdownToHtml(heroArticle.content ?? "");

  return {
    props: {
      articles: [...articles.slice(1, 5)],
      heroArticle: { ...heroArticle, content },
      tags,
      archives,
    },
  };
};

export default Home;
